/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArchitectureSelector: typeof import('./components/ArchitectureSelector.vue')['default']
    BackendOptions: typeof import('./components/BackendOptions.vue')['default']
    BasicOptions: typeof import('./components/BasicOptions.vue')['default']
    CodePreview: typeof import('./components/CodePreview.vue')['default']
    ConfigForm: typeof import('./components/ConfigForm.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    FileTreeView: typeof import('./components/FileTreeView.vue')['default']
    FrontendOptions: typeof import('./components/FrontendOptions.vue')['default']
    OrmSelector: typeof import('./components/OrmSelector.vue')['default']
    PackageSelector: typeof import('./components/PackageSelector.vue')['default']
    PackageSelectorModal: typeof import('./components/PackageSelectorModal.vue')['default']
    PresetSelector: typeof import('./components/PresetSelector.vue')['default']
    PreviewDrawer: typeof import('./components/PreviewDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiLibrarySelector: typeof import('./components/UiLibrarySelector.vue')['default']
  }
}
